language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t my_test_image -f Dockerfile.dev .

# Testing
script:
  - docker run -e CI=true my_test_image npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-423628317456"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
